language: php
sudo: required
dist: trusty

php:
  - 7.0

env:
  - V8VER=5.2
  - V8VER=5.1

before_install: make -f Makefile.travis before_install
install: make -f Makefile.travis install
script: make -f Makefile.travis test
